### ISSUE TITLE
cIoU loss calculation question

### ISSUE THREAD

**Issue by waghostel** [frgfm/Holocron#112]
Thank you for design this great tool!
I found the implementation of CIoU calculation is slightly different from the original paper(Distance-IoU Loss: Faster and Better Learning for Bounding Box Regression)

The ciou_loss() function calculate the final loss with code:
`ciou_loss[_filter].addcdiv_(v[_filter] ** 2, 1 - iou[_filter] + v[_filter])`

The alpha in the paper is formulated as:  **V/(1-IoU)+V**
whereas the code loos like calculating  **(v^2)/((1-IoU)+v)**
I'd like to ask if this is the better design comparing to the original CIoU loss.
Anyway, thank you for the implementation, it really saves me a lot of time!

**Comment by frgfm** [comment]
Hi @waghostel,

Thank you for spotting this! You are correct, this is a typo! I just opened a PR to correct this, and will let you know once it's merged on the master branch!

Thanks again :pray:

**Comment by frgfm** [comment]
The fix was just merged moments ago, feel free to reopen the issue if you encounter other related issues ;)

**Comment by waghostel** [comment]
Thank you :-D
