### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [frgfm/Holocron#140]
Hello there, 

I am the author of [glasses](https://github.com/FrancescoSaverioZuppichini/glasses) what if we join forces?  

May the force be with you!

Francesco

**Comment by frgfm** [comment]
Hi there @FrancescoSaverioZuppichini :wave: 

Thanks for the suggestion! I'm always happy working with new people, always bring opportunities to improve one's methods / ways of designing tools. 

However, what do you have in mind specifically? Do you mean for training procedures? For implementations? or some one-shot collaboration on a demo or something?
